M48
; DRILL file KiCad 10.0.5 date 2026-08-24T21:37:13
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-24T21:37:13+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X7.6Y-9.11
X7.6Y-14.89
T2
X32.0Y-3.5
X32.0Y-20.5
X39.0Y-3.5
X39.0Y-20.5
M30
